theme: jekyll-theme-minimal

# Name of your blog (this will show up at the top of your page and in the RSS feed)
# name: Sample Jekyll Blog

# Short description (goes below the title; it will also be used in the RSS feed)
# description: This is a sample Jekyll Blog.

# Your name, as you want it to appear underneath each post and in the footer
author: JunNine,Kim 

# Your email if you want it to be linked on the contact page
author_email: JunNineKim@gmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://JunNineKim.github.io/synology_dlm_tfreeca/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
# markdown: rdiscount

# The page build completed successfully, but returned the following warning for the `master` branch:
# You are currently using the 'rdiscount' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/.
# For information on troubleshooting Jekyll see:
#   https://help.github.com/articles/troubleshooting-jekyll-builds
# If you have any questions you can contact us by replying to this email.

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
paginate: 3

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]